import type { Metadata } from "next";
import { Fraunces, Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/providers/ReduxProvider";
import LayoutTopSection from "@/components/LayoutTopSection";
import Footer from "@/components/Footer";
import { AiChatBubble } from "@/components/AiChatBubble/AiChatBubble";

const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
  display: "swap",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "MERN E-COMMERCE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fraunces.variable} ${inter.variable} min-h-screen flex flex-col`}>
        <ReduxProvider>
          <LayoutTopSection />
            <div className="flex-grow">
            {children}
            </div>
            <AiChatBubble />
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}

